POST http://localhost:1234/api/circuito/crearCircuito
Content-Type: application/json

{ 
    "nombre": "Sepang International Circuit",
    "ciudad": "Sepang",
    "pais": "Malaysia",
    "longitud_km": 5.543,
    "curvas": 15
}

### Cambiar numero de piloto
POST http://localhost:1234/api/circuito/cambiarNombre
Content-Type: application/json

{
    "id_Circuito": 25,
    "nombre": "Circuito Internacional de Sepang"
}

### Cambiar numero de piloto
POST http://localhost:1234/api/circuito/cambiarCiudad
Content-Type: application/json

{
    "id_Circuito": 25,
    "ciudad": "Sepang"
}

### Cambiar numero de piloto
POST http://localhost:1234/api/circuito/cambiarCurvas
Content-Type: application/json

{
    "id_Circuito": 25,
    "curvas": 15
}

### Cambiar numero de piloto
POST http://localhost:1234/api/circuito/cambiarLongitud
Content-Type: application/json

{
    "id_Circuito": 25,
    "longitud_km": 5.543
}

### Obtener todos los pilotos
GET http://localhost:1234/api/circuito/

### Obtener la información de un piloto
GET http://localhost:1234/api/circuito/obtenerCircuito/25